data:
  host.master: TEN5RWhNN1NXTDB6NFRscmJ2VUloYXdVbk1uSHJrclVwNWYyTlFDQTlTU0dBekZ1VUJjYnlBPT0=
  host.function.default: Y2tSRXZ4bWtZWHNvT3hObVIwM1JWUXN1QUsyRUlpZFluY2NxSFQ1ay1VdXhBekZ1b0JIdlF3PT0=
  host.systemKey.default: dXRfZTNmbnk0UXFpUHFxam1DLUdMZTZhbGtFQmxFR2N0S19IbjhIcmNtdDFBekZ1YkRscUFBPT0=
  functions.createadvertisement.default: NTk0eFZKTi1wdmlHZU9tZUc5eE1XUjd4bjB5OUk3RWJvbF92bVA4SkZGQ1ZBekZ1bEctRnR3PT0=
  functions.deleteadvertisement.default: SXp0U2NWNENRWVlXTEtfOFVqQ21LVVB6b3RGUnU0dDBBb3JYWVM0U2NwZGVBekZ1SGI1LTl3PT0=
  functions.getadvertisement.default: NlhPbTFpZ2tmS2I4UUVUMlN3ZFZQTENyUkVNLVkzZkZJNUtWdFU4VEg5ZGhBekZ1b3R3SmpBPT0=
  functions.getadvertisements.default: bnEycTRiTXc4Q051YkF6THZXN0NjZ29ZeVdKYXRkV0lnaVV1a0k4MnItWlBBekZ1Z254VmhnPT0=
  functions.getpost.default: NHMwMGk2STVVbkUyMHR2SE1LQWZqSEVOelV3YjFXWWd2Y3Nma1JpZzNHVG1BekZ1emlMUm9RPT0=
  functions.getposts.default: WmdKNklRZlpROGRlWFoybi1oV19rRGg3bjlITXBVdk9uNFZRb19rZU5SX3ZBekZ1cTFZU3pBPT0=
  functions.updateadvertisement.default: WEtMbjB5ZG1mN1BlNUJFcFdCZElOUVBqcVFrWWRuNm5DRjNMNUhVZFlfRndBekZ1ZndLdzZBPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-neighborly-func
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neighborly-func-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: neighborly-func-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neighborly-func-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: neighborly-func-http
spec:
  selector:
    app: neighborly-func-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neighborly-func-http
  labels:
    app: neighborly-func-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neighborly-func-http
  template:
    metadata:
      labels:
        app: neighborly-func-http
    spec:
      containers:
      - name: neighborly-func-http
        image: containerregistryproj2/neighborly-func:latest
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: createAdvertisement
        - name: AzureFunctionsJobHost__functions__1
          value: deleteAdvertisement
        - name: AzureFunctionsJobHost__functions__2
          value: getAdvertisement
        - name: AzureFunctionsJobHost__functions__3
          value: getAdvertisements
        - name: AzureFunctionsJobHost__functions__4
          value: getPost
        - name: AzureFunctionsJobHost__functions__5
          value: getPosts
        - name: AzureFunctionsJobHost__functions__6
          value: updateAdvertisement
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-neighborly-func
        envFrom:
        - secretRef:
            name: neighborly-func
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: neighborly-func-function-keys-identity-svc-act
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neighborly-func
  labels:
    app: neighborly-func
spec:
  selector:
    matchLabels:
      app: neighborly-func
  template:
    metadata:
      labels:
        app: neighborly-func
    spec:
      containers:
      - name: neighborly-func
        image: containerregistryproj2/neighborly-func:latest
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: eventHubTrigger
        envFrom:
        - secretRef:
            name: neighborly-func
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: neighborly-func-function-keys-identity-svc-act
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: neighborly-func
  labels: {}
spec:
  scaleTargetRef:
    name: neighborly-func
  triggers:
  - type: eventgridtrigger
    metadata:
      direction: in
      eventHubName: neighborly-hub
      connection: Endpoint=sb://neighborly-eventhub.servicebus.windows.net/;SharedAccessKeyName=neighborly-hub-policy;SharedAccessKey=mPoeaDc40BaZlnCjY5ia+ZKsnO5Ge8ex2+AEhIt9pf0=;EntityPath=neighborly-hub
---